from fastapi import FastAPI, HTTPException, Request, Depends
from fastapi.responses import JSONResponse
from contextlib import asynccontextmanager
import os, json, sqlglot, asyncpg, jwt
import sqlglot.expressions as exp
from sqlalchemy.orm import Session
from dotenv import load_dotenv
from database import sessionLocal, User
load_dotenv()
from sqlalchemy.sql import text


@asynccontextmanager
async def lifespan(app: FastAPI):
    app.state.db_pool = await asyncpg.create_pool(
        os.getenv("DATABASE_URL"), min_size=2, max_size=10
    )
    yield
    await app.state.db_pool.close()


app = FastAPI(lifespan=lifespan)

EXCLUDED_PATHS = ["/", "/docs", "/openapi.json"]

def get_db():
    db = sessionLocal()
    try:
        yield db
    finally:
        db.close()

@app.middleware("http")
async def middle(request: Request, call_next):
    if request.url.path in EXCLUDED_PATHS:
        return await call_next(request)
    token = request.headers.get("Authorization")
    if not token:
        return JSONResponse(status_code=401, content={"detail": "no auth token provided"})
    try:
        payl = jwt.decode(
            token,
            os.getenv("JWT_SECRET"),
            algorithms=["HS256"],
            issuer="nagar-auth",
            audience="nagar-services",
            options={"require": ["iss", "aud"]},
        )
    except jwt.ExpiredSignatureError:
        return JSONResponse(status_code=401, content={"detail": "token expired"})
    except jwt.InvalidTokenError:
        return JSONResponse(status_code=401, content={"detail": "invalid token"})
    request.state.username = payl.get("username")
    request.state.role = payl.get("role")
    request.state.user_id = payl.get("user_id")
    resp = await call_next(request)
    return resp


@app.get("/")
def chek():
    return {"status": "Running"}

FORBIDDEN_COLUMNS = {"name", "phone", "email", "address", "aadhaar"}

def validate_sql_ast(sql: str, user_role: str):
    try:
        parsed = sqlglot.parse_one(sql)
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid SQL Syntax generated by SLM.")
    if not isinstance(parsed, exp.Select):
        raise HTTPException(status_code=403, detail="Security Risk: Only SELECT queries are permitted.")
    for column in parsed.find_all(exp.Column):
        if column.name.lower() in FORBIDDEN_COLUMNS:
            raise HTTPException(
                status_code=403,
                detail=f"Access Denied: Query requests protected PII column '{column.name}'.",
            )
    tables = [table.name.lower() for table in parsed.find_all(exp.Table)]
    if "health_camp_records" in tables and user_role != "ROLE_HEALTH_OFFICER":
        raise HTTPException(status_code=403, detail="not allowed")
    return True

@app.post("/query")
async def querydb(request: Request, db: Session = Depends(get_db)):
    username, role, user_id = request.state.username, request.state.role, request.state.user_id
    user = db.query(User).filter(
        User.username == username,
        User.role == role,
        User.user_id == user_id,
    ).first()
    if not user:
        raise HTTPException(status_code=404, detail="no user found")
    body = await request.json()
    sql_query = body["sql_query"]
    try:
        validate_sql_ast(sql_query, role)
    except HTTPException as e:
        # Record blocked queries in the audit log before rejecting them
        try:
            async with request.app.state.db_pool.acquire() as conn:
                await conn.execute(
                    """INSERT INTO audit_logs (username, user_id, role, sql_query, status, block_reason, ip_address)
                       VALUES ($1, $2, $3, $4, 'BLOCKED', $5, $6)""",
                    username, user_id, role, sql_query, e.detail,
                    request.client.host if request.client else None,
                )
        except Exception:
            pass  # auditing must never mask the original 4xx
        raise e

    async with request.app.state.db_pool.acquire() as conn:
        try:
            results = await conn.fetch(sql_query)
            data = [dict(record) for record in results]
            await conn.execute(
                """INSERT INTO audit_logs (username, user_id, role, sql_query, status, row_count, ip_address)
                   VALUES ($1, $2, $3, $4, 'ALLOWED', $5, $6)""",
                username, user_id, role, sql_query, len(data), request.client.host if request.client else None,
            )
        except Exception as db_err:
            raise HTTPException(status_code=500, detail=f"Database execution error: {str(db_err)}")

    return {"status": "success", "row_count": len(data), "data": data}
