---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nagar-minio
  namespace: nagar-app
spec:
  encryptedData:
    accessKey: AgAkzyNmX+eDUYo4MF2lI/QFzQ07A09H3opTMDTuBG06S805PY+YGuih8VSNO568XOt9KF5gnBBcNSQv1cSlxvCMp+PrxvlVUZ+Iivvfm/LZf3RZA1Ebva0LzTHT9S+HQ1fCoQepbf5fPZAUST6QD1Ao3W77vJEyvqKAExt6RbczBjiO1EswK0a0HAYFCPj9ek0z9VWQrmwGwXm8XBYOT78FqqHs17XHZkD0l2M2xRh42lfba/3BJsSsrTLdIcokoILxH+TqDY6SD2cRVqI9bwOo1kgHLPE33IQAdTkzSrL0T2I8YTU4icT4hBFto4CwY4+Tw+rNK0YwRaVERwKEwJDKDU3qweM5BoneTOUp+B7D/UXV4+v2ae0SDFG/juCriYsd/2V33R/K2yPFCHEXtg7gj3QpK/coaMiECa0nL/DFBxcR7G2vBTWBGUI2E4sMY8RXx4pPcdhaa8t6qO5aO61DxZYYwiOkm2GRypByLLNWBqnFMgovztyBZbHqPJuhS/D1+zKUUWLXeocrHFF/Ri4BcdkQoYtZUgBto7nEsT9pEw1Het6y43MO292FQf6AXKca60FrvJY/VK89/G6NuBGfu6dASUqC6hT8mvktP8HNmUpvJK0ikwPKPAA6AMJfjzJwFhT+gzp3bMmDdUA3+Rm3PdfvarNHRjwTY7e/iiQgc5X56SMUjIIAInz/wD2i3m125AxdG3l6FBHE/0F7LXzVjLUbNfk5lZlJatyA1t9owA==
    secretKey: AgBlBZHEjaiMmYffEUe4rulgVRV4BxPMARbgERmokM+mdpi60eWFrUIUWGqmPvu4nJWySM0RhQI3sjMA3FytZlQGtpj+E4PhCgRcfvyvNoZzXl/TtqOVmHyqr9tgqqh9nyi/aipcUZCEy3OgWxIEyQ7x0hwzvwZiZzSfgOtjvf7adC4M7dmTRIlnQmphZRDxQSAXkpvVsyswTpk3WxG9y9Pn4tzOOPHF8FYTCht1uXrhRz9vbEhpeHpGi+3OEBLqdTsDNbL9zz334bCm17CKtWgEEPqSjR246QrdbhoUFTXQXU3BEKpv+QWfL2UKKHHj8hbMAV95+6QxSjzs9BLK+vwz/JNvzvCIrq12cULHtFBhiwJWeU+YfkAGmxfkuccohsflYQ6mDQo5ahoreC1ZdP4zSLaXxeEDmJkdv+W48ZGYuR3MYw6NXoylrFPvGa604FKuHw08Wq7DywsVMZ37bfT21VH1ep8+yVHOTkHBzSq3QAj4gIzg8b8e0zpJ8x3DV3VEZ37c+VgBHQiL12u0wKRRuryfdKZE/bIAPv6Tgi+2GtAbtYON4OoVfFMBbvUByuyqtiP78hhtk5s6qgY2RSQWnVAqyraUgvo/4B1K5eTMjchrHGiTZk9KFPKTcnM6odNbztf833EomS7ZsrqFIxoABW/tU5jbQNnosc9znIem/igjzgsslmzCDPfK7XQ3m4OpBm1z7SamBbtdBBelfZDVAMGkkSeZRBILFBIk+2E6bLFVQvmBdYXoytJYfcN7xHKyiI8NzzOJJgmS0QnowGVz
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: nagarvault
      name: nagar-minio
      namespace: nagar-app
    type: Opaque
