---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nagar-postgres-app
  namespace: nagar-app
spec:
  encryptedData:
    databaseUrl: AgCON2i0BClMe0+MmvCixn3C8gd06bJts4TGCijaKCtin7GibIMNNLhs76VMNYzKZ88AMHLdeZb6Xal7/2EAAYjVHOpP3D5sa9zjNyfAbxNnRyxz1S3PgkZvvdJ9JoxPtjbzWOjD586Jubc1jN9zOa9pDmSKllnDjYxTF16OnJfyaO69cQ66XcxRxMfFurQbom0GYUoIZYDwYrXNcwm+HIUKl+omos8t6s7od2mSzVCG+IKMkAWJif7lxvSZuVXdjvSAMDxEbSDvN0zWEzmgKMRUvBFECSDh0QnpvuPde/jsajArzKwl+UZL9p+PlKwuzuDZOLhPFLsGlvxTfPBzEFXGOnjO+CVPRr9UEyOQ0YxAdOSOt5pVWg/NS0oAC0Dg4wo53PPqRNQfN3ORkEaYkY3ppRjWlxaikq8lvrdyw03jGHxOMZLj52NlqDJwPUVCtYcq3fotnzDUJdTxA0a2HRvCbJkvcnmCoGWSwInUJMrH9Wvc/GhXrdX5b33bBXA3JkIu1V6au8cgi0z7qFEwxxrMtACHTAwP5FtHlJLdVgvz9cTJ0s9Ki0Rb2kWWWQ3KmHgx6rf0zuygS9z/AhOGh7x3/OGgmtdYvYTH5MU/BFlpi3lIMlDOLUX9Xa6oX+fFcwBFXokXeHW6Ntn4TZ/xdaEsdKG49Cino5Yj6/+6lVX5PaEMGKkTPxOJUtjlyxSEUDzZwXr2GjCI56E3ozOYTdoCigf2xV0YI3LiaJWWHizODlCvz/i2oT6SCHMhzsrIC3TjKe5NZte20Jt/WbV3nl9WAY7i1eYjnBn+myoC4b7M5Y46Mz1sZCeQ1bocA762jE8Lsr9+gSwF/xLGpcPn
  template:
    metadata:
      creationTimestamp: null
      name: nagar-postgres-app
      namespace: nagar-app
    type: Opaque
