---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nagar-jwt
  namespace: nagar-app
spec:
  encryptedData:
    jwtSecret: AgCX+Lq0G0sjmHrodSx17kkxLtIaRUJr7667Kwp+1ig13GO/GiQVv1+jDVIWzWsRs6fnceU2g5isNkphKKZSLdClcxzKGVwVeCpMoSX4TOFKVh2WetLHgD7fzzjrXvxyo/4FJw7Kwtc6uwlJlSEHSoEH3S9EoFFkYXWUbhPXg9tYyY0L0r1SajmgBm1DHWcTc9VADjVkSYjwJ6UxG1GR3IUxPrZ9RmTdn/swHIN/QD9H26iYTenjzFZtHPI0qaZ26H3o/Sr/1AjwaC4Snm6g5aGvUU4w7vAil0w0wpF/OA88+jPJ/53jrMHsbb2SMllhyYHc7NRWRWafslXA1I08iGHLobRdg02bWt15W6DMGrr18XFfBbYu/nho/Znu1ApCrkuBwerj2eE2Cq9wPbEhTbzQ5ayMVUL4O8tT6fGVQuZa5AhVYfzqCF/TU7lREi9LoyTz7PhJJnobyqupQVHYG0AyrxAuiswdQd894RGu6UZpCU5A6hzjGzLM5ECh14++K2OnBLflRQSuyP1F6erw4Qs9oJIUvia8LJ1k5TeY1taFV/BDJprgU8pgBDzO7xciKO4aUEFnh+knM58OQ1cSlz1U1xr6SSaKtUHgBmw41Uq0xvWM7eMTC1jXbZFNmJMOIyXNlmYhab0xs/Sf4cY5DqH3F4RQ0/saN7YFyicT9hd4TfK1Oa+L1x3trY6U9vDTgSJOJhOJlac+IN6FZ0pMXYIs/02F0n5/dooss1ZiE5zXZqxIn6sxreTKySEuSAZzR8l1Tqi2nDwlvRcmnDOMKqf2
  template:
    metadata:
      creationTimestamp: null
      name: nagar-jwt
      namespace: nagar-app
    type: Opaque
