---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nagar-minio
  namespace: nagar-app
spec:
  encryptedData:
    accessKey: AgCKbAsGWNtbV6QAhVAX3dipaqgank5TAVxRm2OIEx8KgeANEaam77EHzGpvzpWpvYpgZKzd6dIGMm2p5zzvb3mVA63ud7F40LfkNqyimnBcGjv+wNQdiVDLuHc0eV65JfYealNAAwtKjom51loxNjA/cUR4zLe30f2hJnWEruxQ5dqJvTMk5jyvPUTBIZQ3yON7w95J1yMhrbwugGcwxgNgFpfLC/SPodq1KQJWWwC9tL5fvVEly2RBoaQuIQSoAK/p0IpEGzhAz+/NTUu6h0M65QuzZlefMc2GpTofoNumX6DQ5/SgyzlWlBnqMsSES9P1/OKJxWG/voepziVoEiTkZrEEtVaa4ywJ7VFKK4day8ASoKvCSMeckU4gz4AWlyU/+pp7qv3rvVp+nvq8fFF7R5Hw8y9p/ikge8Kp9cl3unJc5ZTza1svCj82KNeS6nYMMiTk8b5X1X/a8MI+f7nu8O3UUib3mXZ/8Q6szKRVLkI3bRGWkDu7o9i8qb3nvUU15PpQxPJ35lfLLLqgq+NlsyzIgFV2SFdObK5CAHMi9W7dG6TXlW+/k37MXzy3iVZBGNr7QTvO8SX7c3vtfiBwjV37Ku0v1D6wahBxr+DSWWn77aOygLOaWDjVN23smq37R5kbpunEy3aQoJvG7zleyuAq/4qPIAWZADpeshAuE9+lHwaHB98355BhGp3eqhj1dpFeQrhvsXli9Lzt/p4AzfOOBX48kAOI8rz9XeGQxA==
    secretKey: AgABLjc30xW/x1XYTxGdQNwLM9EcPpwRctB/2+5UhGrjGa+3GEuGm3OILMmu1G8VJuAdidaRFUzGu5FfaSABn3l3H65KCPz3zyMifb5+tWlL21GIk9h+BSTQCHnDSu79do9PuT0j5WiULN/F7Vc5+vWOXjPg+V0bGAUfy3jN8dqcB+DgM4fVumA0JxUWAVgbCQixn+DS4n4PyoQ48iTPuDtP2wykUchSOuck3iQWcUNjy/3TcEJkf/JYPtsWC4SM+bu5P/7kYI+E5ob9d24Uf0EFBU347wHh/FDm6t6ClYbMRnRjn2wsCuS0xOrHOOlRihNAus0gBa6ftv4i5O5Fi6ynW0mwHMHotx94nkuYhU14khbUsMwpv7pUuaIMbONKkGMbPBSozex8uM9QWXlsEnFTdIERqlqSh+j1uBRQcnKwHXHOj7M52CmnIFsdPfdVb2A2xJG5YEKrHElmEnBfWl0A5uW+wcG7ndYSnpU/yGD4Z7FSIPr9sUHY0sEuJTlvtIbWfq0i/7U9t1sKqShupOVbz111wJLY+hxy6Fq4R74gIxAaofXXtV1y0kZRKx9WdYIqhlIBpK8RIbzkrTznfemn+hpOQbvCtWZjugHTXTkmOXJ3L9FC3tX62hTXDvoJM5M2UVaLDLuvL/+bzrN6E21bpJOO4puRHASgEL2hTkXBLA5Qt3y7lyWXbsT5ZzCnMv/ecKImhGr4Z/P/gkq/v8/YZBbUdNuU11GgGzSiwvUSgs0WKEIOe5OD+f4u1HTKbclPUv03kH9/O37jQWnjGBzw
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: nagarvault
      name: nagar-minio
      namespace: nagar-app
    type: Opaque
