---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nagar-jwt
  namespace: nagar-app
spec:
  encryptedData:
    jwtSecret: AgB56JCtn7VnVJcfewNDFcb+FLioLg8bWwPnNhfQIMif5/q6oFYi7MAbS5+vrP6jm9sLA5mUMqeMVpXyneMcQIdP1b9Swt0iARcW03OwL6OeX217r76MtQsh2bbxKnxO7gwlLbI3vYq884lJegPxZkupjGqbzk7I9H7LqpbukKWag2sexzT5paBwKuBKQ/bnlnEmgLNIE7tQzqF6Cdqh0zrWsUwfLfffU7CMvghGsEqV8Bc4NLYmmxXMSMlV2zilcfrDaDaAJf8ca+HIC44jZ7p/NkGlAAZXCM8NW1NVBsKNW+4bftmWjD1cMbVd6SNXiGkghWJlHpcbohjB7SHbhRrNWl809tm++pZ7PKqhpFQT/ZYW111dp+B/HxKR899umjWQVGEzfn1V0aWfdk/vPZIkNEdGfZk3a8uMmQ3NES2+zuFpwMnNmawXvo4x9c8xys0XT9G2pJ9wN6V4lpl4OlM9IVu0DwPNG7NJu+UMxB9+mkRzWsHewy33/Jb+UP4lpv1JxYsx+AQ0JmJNtA/yxnxImik0th45KVT8jfEiJdXfznrgbZOcRhKaadkuZj9TOdi5GV4KfRlvbRTECVDGLMrM2cT5ukBUgraefCovV+uz5gdH9XBZGnerQcSN1vpcNhJMvUTabX9dveqr1cE5xPNX1jF8/npHETIWKLV8i4PaPh6iediXGPODyB/4oPp4EKbRh/a6dROt+DLksSviqXn9TFXnYn111Qd4lSDFnNQCzGBl+G0zK1sl9d+0XnzJuUFu9q1zOiais7TPbt48Nvr6
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: nagarvault
      name: nagar-jwt
      namespace: nagar-app
    type: Opaque
