---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nagar-postgres-app
  namespace: nagar-app
spec:
  encryptedData:
    databaseUrl: AgBZRM5rt8lr0bTbO+GGIYUeum8eh+uE2270tX5HYlw1QKzALN37uegSHiIdwcyYy6zpfrPf1xrQJ/IbHaFpnomQzP1mVe38Ea3tnTBHA07JeERcTIWOYNCyQh0jTrUYsgBdI6A74xuulKHGSGXu9NQihEL3GJb+ZBvnf/kAPHC1mzXjslT+4JuSWwkGz9gOhRL7Yq+tQ87Os5btYIQuCfJDkpuwECtmvwFGYNxuBSmIuHWMONdyM9QuSNZQwjTXeNh5zACuabxiM7UiM+9MW/QTJpeJrdnMVGfWFkIoXS7GUDhe19YyebHZeZMG/mn94slFC6a8PB6VErL9Zbqqjl+OIKzYmh+x2Tza7BQ1DgnjIIMbz9J0vvaYLwOLuNCfdktdhyNVS20WRSUtxRpMz94oTDVC86+MfrcYt94EALwE8hr48GUUOGhlHvbR3FEuligoFx0jOvLbP1gYZiSydeeedATgOCdwJqwR273Vb4m29djWbxAXRNvRmNltfnZc4WiJJ7dLpK+rU6v5oobZCVI8Ahxk/uOwF47AiSLA06ADmJ+ec7vheiZsrAaKfCBeMd22ZjaEIvBgEuS9QgnilgK7zWi05m2pWeSwxed1KMZbDuIzQyfsHzSSy1daQfRg9Gc5oPJQTt27LMUAXcLeZR0Dp2MrUkgMjkivDxvbWDGQhNChVBwgxtwP8joc4H6kiYD77EwspiNWneC0EBeIlLTofJDBBxmyiCMNyu1TPtV1egqcQttNFPG+3PB0wGag+BZoiuRfDbWriXWRElaG5Md9hSnd0FwBPacEs4Mqan19/pWcR3QjNiz+8o260ctx0edV+FNM5hOho+sn/ZY8
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: nagarvault
      name: nagar-postgres-app
      namespace: nagar-app
    type: Opaque
