---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nagar-minio
  namespace: nagar-app
spec:
  encryptedData:
    accessKey: AgBbg8/BHJLtGtcvRATevz3FFAA4KnBviF7d5YSglM/QrRwhe/QQUhiotlWR+JwJRr82Ph4I9mfmHVnVQStdt9v/wVVLHeSAbW5DVfDEP5VlsE77ZXODzIKF3I2AIcC0WIiGhDiOTxLqBAshYKCIKOxnXXiGnZAzScVQ1y39ChsbMXa2U8FOvDxttmDdQkF2y704GeQli+LU20XntYfGELd3AyYoC74kBIlbYUKvTKFOFnfe95GuNsrZtt+EFedaGIEQVMQESotaeKlvIxlaUkMnl3eVagNMYH4xyHBsMyFYnboPSDdw0Ut8IbYWNeVmWkGBUaUopsRpK9UgXa/vjic0n9hM6z8OMaeVBgMJf7BtSWgIz2XjlXGY9KHACzdnrXp01fQsoNBfNe4vGD/+GJ9uLJan3WJUJcFEvUV0ZDg12zQVk8PH+aWfWKFWGkygh5Ckx/f+Oj3/g86Jo1M5Mc3s5qQeji6vfsxl633dZd4buH37DzM7Kq30SUG0bKJnCaVVyn30Q8QGHvyt6ZmgFfoUjMjawwdczAjqceC9ykdtF3dp5vIF5H0lWMovLxh1eD3dbQ3nUydGLO9z62LKA6SYrg/sncX2w3DHpjHIH9iPjByYYBaAIzo0tiEbAvlkVyF5HTJwqFazl1mVBJSK24GNfSG4uBDVwB5monJG38OEUNQHsjoPF2fl1DtoWdciQ/pxwG8iB6sS/ZpVRppYh1+tBrNs+bIm71M=
    secretKey: AgADY1HOc/7MsRj1dtx4za8kTJN2M+exyKSWPf9irO+nI3/MVgMoMBUjcIkcLeTdgqEAab9kHE3efrGKSxdYQAy39Ed/BaEkr7wq0J+U7qOxFvXVPqeqQc3BC+nJvQXzH4Ni8X3f6mj7USRJV8c1fzLE+yjdy3EcvhOGnVk2hWtln3hsEJjxxGLLpZn9I+7ipYFOHbKQpP13Yx2YZnxn9hjJtYgqTjKtsPEZeNNC+RXRezj7wWM95+4UPxF27Xbm+OlEKIfXIzTCIzPgat8bRcFnbkcexuNDW8Af29oJCYIAXw8iFIpmDS9li4Thj9Cnuy1RmcdhmgS9q9z5JElzVPoD/YB/QuiSx7gYw8ZuGv/2d36jrbr2BUASkqr+iqn2pfgxe9qKzgpbXGXVvn/Vjl4ra2KA46CUUzOhbiE4TtoXpdxEHnNZfdNvkwiPQtOXsNxwHjzMPxzmQezpOxn6rdJlxEWvsoPhuzO4KhGJPeCCzWltgU797+jEDqXQ/vbJytURLOmgiIl5BZLwm4nkrD8suHaxdvwuvvaRIl7t8jHEmX/4qxY6KmIJrwUd/ivZXSuU6mqsYkoOVjag9i9Nrxn1HKoR8wej3YIIIVwmMAC+LOiKj88XkQW9cSfZZ0uCtDKsS1rjdszhOeAO/iRwloxW25mvajumd2Qybs9b6Cmi5/NzwabpmTHdz0YGsylIMVN5G1R4kMszKqadniAViORfilucePPq0WFcJES5HVNl2F9IUbDo4LPbo5ibXjXxWv4=
  template:
    metadata:
      creationTimestamp: null
      name: nagar-minio
      namespace: nagar-app
    type: Opaque
