---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nagar-grafana-admin
  namespace: nagar-observability
spec:
  encryptedData:
    adminPassword: AgCMuXlgWRXqS9Wvx5bsFeYoLqh8mdUp6eqgi/N3W9fr+kxCX11Hw8mAAa29PqHXZrgPAA2q6+SKkrEqX4eZVn6W/rASTpF+LhJ+V8Ejl6wLRYB4ccUcxyHU1kBduOoAWcxbmcz3uYDxuqyL7ELiBpSY83PHZdo5o/De7i1ZEbrpdjW1U6j0eSCzLsBBkY1hpVV6obG0OnboZWnQWHx/Axt4GtofTxyByfWhgDiRzkXIlDx2ll32v9pHlc/350vIu4grgozfLb3/Wdk8cpCcjgErwrM12AbhnTkWjIngABtALIbsZtJw1ZfDEyb/t9CtMnVlCXAVjHWYvocrJiw9urSCu4azxJSiNYAtPJ9nnmRWLD+X6WLhacUuH8PnLFl7PRPaZ/E9QkTdxig4AcJxmpM+ZXM4aAMtZ4WsITGJSShG10JsVO7mryb+j6xu5RGreNI15gJemioaLozKXnGR0AbleWgDsgdBXioEVA+w82PRkLe1Azs8CWDuRrY5IVRb7J9QWBNEhHb605R4xAC0jPiM/JSCD0X30pJf+DQoUbJk/due6eI5sSnWfxzhX4I3GActiHA/zjwIGhKbyv7lIaPf9RfL4MJMelxax+comO0y+Yfq/poGra0P5hobpbdTk5Q+3GNv0SFeGWQ2EPjU1M+lPnAwEXWQ+z+DQjqZ/StYlyo4h/Wjjo+gKZVFoYxgSsDB1Csp9VpbPT+UWc9hTrU9OSrRq8ynU7g=
  template:
    metadata:
      creationTimestamp: null
      name: nagar-grafana-admin
      namespace: nagar-observability
    type: Opaque
